server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/base_hotel?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.open-in-view=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=reservas.royal.suites@gmail.com
spring.mail.password=yeps zwma oinr njav
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

application.jwt.secret-key=bWlDbGF2ZVNlZ3VyYUpXVDI1NkJpdHNMb25nSGFzaA==
application.jwt.token-prefix=aG90ZWxfdXNlcjpob3RlbDEyMzQ
application.jwt.token-expiration-after-days=1
application.jwt.refresh-token-expiration-after-days=1